name: Codacy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies 3.10
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 flake8-pyproject black isort

    - name: Check Python 3.10 code compatibility
      run: |
        flake8 app rosemary core
        black --check app rosemary core
        isort --check-only app rosemary core

    - name: Check outdated dependencies 3.10
      run: |
        pip list --outdated

    - name: Audit 3.10
      run: |
        pip install pip-audit
        pip-audit

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies 3.11
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 flake8-pyproject black isort

    - name: Check Python 3.11 code compatibility
      run: |
        flake8 app rosemary core
        black --check app rosemary core
        isort --check-only app rosemary core

    - name: Check outdated dependencies 3.11
      run: |
        pip list --outdated

    - name: Audit 3.11
      run: |
        pip install pip-audit
        pip-audit

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies 3.12
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 flake8-pyproject black isort

    - name: Check Python 3.12 code compatibility
      run: |
        flake8 app rosemary core
        black --check app rosemary core
        isort --check-only app rosemary core

    - name: Check outdated dependencies 3.12
      run: |
        pip list --outdated

    - name: Audit 3.12
      run: |
        pip install pip-audit
        pip-audit

    - name: Upload coverage to Codacy
      run: |
        pip install codacy-coverage
        coverage run -m pytest app/modules/ --ignore-glob='*selenium*'
        coverage xml 
        python-codacy-coverage -r coverage.xml
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
